# Generated by Django 4.0.1 on 2022-06-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation_salle',
            name='date_reservation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservation_table',
            name='date_reservation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
